language: c

matrix:
  include:
    - compiler: gcc
      install:
        - cmake -DCOVERALLS=ON -DCMAKE_BUILD_TYPE=Debug
        - make
      script:
        - make test
      after_success:
        - make coverage

    - compiler: clang
      install:
        - cmake
        - make
      script:
        - make test

