language: c

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
      - cmake


install:
  - cmake -DCOVERALLS=ON -DCMAKE_BUILD_TYPE=Debug
  - make

script:
  - make test

after_success:
  - make coverage
