language: c

matrix:
  include:
    - compiler: gcc
      install:
        - export COVERALLS_SERVICE_NAME=travis-ci
        - export COVERALLS_REPO_TOKEN=m3LsUG5LILV38n8moeBJlwi0EPbrBdS6X
        - cmake -DCOVERALLS=ON -DCMAKE_BUILD_TYPE=Debug -G"Unix Makefiles" .
        - make
      script:
        - make test
      after_success:
        - make coveralls

    - compiler: clang
      install:
        - cmake -G"Unix Makefiles" .
        - make
      script:
        - make test

